# Machine Learning and Statistic
***

### Introduction

This document have been created to complete Machine Learning and Stadistic task assesment using Python and Jupyter Notebook. 

This projects will be separated in four different tasks.

### Task 1: 

<b>Write a Python function called sqrt2 that calculates and prints to the screen the square root of 2 to 100 decimal places. </b>

We can calculate the square number of a root using Babylonian method, which sometimes is called Hero's method after the first-century Greek mathematician Hero of Alexandria who gave the first explicit description of the method in his work Metrica [2]. The formula is  derived from (but predates) Newton–Raphson method and can be represented as below:

$$ x_{n+1} = 1/2 * (x_n + ( {S}/ {x_n}))$$


### About Babylonian Method 

The iterative method is called the Babylonian method for finding square roots. It was known to the ancient Babylonians (1500 BC) and Greeks (100 AD) long before Newton invented his general procedure.[3]

Here's how it works. Suppose you are given any positive number $S$. To find the square root of S, do the following:

1. Make an initial guess. Guess any positive number $x_{0}$.
2. Improve the guess. Apply the formula 
$x_{1} = (x_{0} + S / x_{0}) / 2$. The number $x_{1}$ is a better approximation to sqrt($S$). 
3. Iterate until convergence. Apply the formula $x_{n+1} = (x_{n} + S / x_{n}) / 2$ until the process converges. Convergence is achieved when the digits of $x_{n+1}$ and $x_{n}$ agree to as many decimal places as you desire.

The idea is simple, starting from an arbitrary value of x, and y as 1, we can simply get next approximation of root by finding the average of x and y. Then the y value will be updated with  number / x [1,4].

In [15]:
# Define the function to calculate the square root of a number n

def sqrt2(n): 
  
    # Use x as initial approximation (1)
        x = n 
    # Initialize (2)
        y = 1          
    # e decides the accuracy level 
        e = 0.000001
    # Create condition for accuracy and calculate the better guess (3)
        while(x - y > e): 
    # Get the next approximation for root using average of x and y
            x = (x + y)/2
            y = n / x 
    # Return the (approximate) square root of x.
        return x
     

In [16]:
#Ask for square root of 2 and print 100 decimals [5]. 
"{0:.100f}".format(sqrt2(2))

'1.4142135623746898698271934335934929549694061279296875000000000000000000000000000000000000000000000000'

### Task 2: 

<b>Use scipy.stats to verify the Chi-squared value of the table below it is approximately 24.6 and and calculate the associated p value. You should include a short note with references justifying your analysis in a markdown cell.[7]</b>


The Chi-squared test for independence is a statistical hypothesis test like a t-test. It is used to analyse whether two categorical variables are independent. In order to find Chi-square, we are going to use the SciPy package. SciPy is a Python-based open-source software for mathematics, science, and engineering[8].

\begin{equation}
\chi^2=\Sigma\frac{(O-E)^2}{E} \\
\text{where O is the actual value and E is the expected value.}
\end{equation}

|              | A   | B   | C   | D   | Total |
|-------------:|-----|-----|-----|-----|-------|
| White Collar | 90  | 60  | 104 | 95  | 349   |
| Blue Collar  | 30  | 50  | 51  | 20  | 151   |
| No Collar    | 30  | 40  | 45  | 35  | 150   |
|------------- |-----|-----|-----|-----|-------|
| Total        | 150 | 150 | 200 | 150 | 650   |
    
    
 ### About Chi-Square

The Chi-square test for independence is also called Pearson’s chi-square test. Chi-square test for independence is used in science, economics, marketing, or other various fields. There are three ways to use the Chi-square. The Chi-square test for independence shows how two sets of data are independent of each other. Chi-square of the Goodness-of-fit test shows how different your data to the expected value. The test for homogeneity determines if two or more populations have the same distribution of a single categorical variable [8].

Degree of freedom

You can find the degree of freedom in the third returned value. We are going to use this to find the critical value later. The way you find the degree of freedom (dof) for 𝜒2 for independence is different from 𝜒2 Goodness of fit.
For 𝜒2 for independence:
dof = (the number of rows - 1) X (The number of columns - 1)

p-value

P-value measures the probability of seeing the effect when the null hypothesis is true. So, when the p-value is low enough, we reject the null hypothesis and conclude the observed effect holds [9]. 

Depending on the test, we are generally looking for a threshold at either 0.05 or 0.01. Our test is significant (i.e. we reject the null hypothesis) if we get a p-value below our threshold[8].

In the example below the p= 0.00041 which is lower than 0.05  therefore we reject the null hypothesis of independence. 


Contingency Table

A Contingency table (also called crosstab) is used in statistics to summarise the relationship between several categorical variables.



In [24]:
# We create sample data using Numpy dataframe and we will store our data above in a variable called collars

import numpy as np

a1 = [90, 60, 104, 95]
a2 = [30, 50, 51, 20]
a3 = [30, 40, 45, 35]

collars = np.array([a1, a2, a3])

In [27]:
# SciPy’s chi2_contingency() returns four values, 𝜒2 value, p-value, degree of freedom and expected values. 

chi2_stat, p_val, dof, ex = stats.chi2_contingency(collars)

print("===Chi2 Stat===")
print(chi2_stat)

print("===Degrees of Freedom===")
print(dof)

print("===P-Value===")
print(p_val)

print("===Contingency Table===")
print(ex)

===Chi2 Stat===
24.5712028585826
===Degrees of Freedom===
6
===P-Value===
0.0004098425861096696
===Contingency Table===
[[ 80.53846154  80.53846154 107.38461538  80.53846154]
 [ 34.84615385  34.84615385  46.46153846  34.84615385]
 [ 34.61538462  34.61538462  46.15384615  34.61538462]]


References:

1. https://www.geeksforgeeks.org/square-root-of-a-perfect-square/ - Babylonian
2. https://en.wikipedia.org/wiki/Methods_of_computing_square_roots#Babylonian_method - About babylonian
3. https://blogs.sas.com/content/iml/2016/05/16/babylonian-square-roots.html - About Babylonian SAS
4. https://github.com/ianmcloughlin/playing-with-jupyter/blob/main/playing-with-jupyter.ipynb -GitHub Ian
5. https://www.geeksforgeeks.org/precision-handling-python/ decimal
6. https://stackoverflow.com/questions/58170806/how-to-compute-and-store-the-digits-of-sqrtn-up-to-106-decimal-places

Task 2
7. https://en.wikipedia.org/w/index.php?title=Chi-squared_test&oldid=983024096
8. https://towardsdatascience.com/gentle-introduction-to-chi-square-test-for-independence-7182a7414a95 about Chi
9. https://towardsdatascience.com/running-chi-square-tests-in-python-with-die-roll-data-b9903817c51b


