# Machine Learning and Statistic
***

## Introduction
***

This document have been created to complete Machine Learning and Stadistic task assesment using Python and Jupyter Notebook. 

This projects will be separated in four different tasks.

## Task 1: 
***

<b>Write a Python function called sqrt2 that calculates and prints to the screen the square root of 2 to 100 decimal places. </b>

We can calculate the square number of a root using Babylonian method, which sometimes is called Hero's method after the first-century Greek mathematician Hero of Alexandria who gave the first explicit description of the method in his work Metrica [1,2]. The formula is  derived from (but predates) Newton–Raphson method and can be represented as below:

$$ x_{n+1} = 1/2 * (x_n + ( {S}/ {x_n})) $$


### About Babylonian Method 

The iterative method is called the Babylonian method for finding square roots. It was known to the ancient Babylonians (1500 BC) and Greeks (100 AD) long before Newton invented his general procedure.[3]

Here's how it works. Suppose you are given any positive number $S$. To find the square root of S, do the following:

1. Make an initial guess. Guess any positive number $x_{0}$.
2. Improve the guess. Apply the formula 
$x_{1} = (x_{0} + S / x_{0}) / 2$. The number $x_{1}$ is a better approximation to sqrt($S$). 
3. Iterate until convergence. Apply the formula $x_{n+1} = (x_{n} + S / x_{n}) / 2$ until the process converges. Convergence is achieved when the digits of $x_{n+1}$ and $x_{n}$ agree to as many decimal places as you desire.

The idea is simple, starting from an arbitrary value of x, and y as 1, we can simply get next approximation of root by finding the average of x and y. Then the y value will be updated with  number / x [1,4].

In [3]:
# Define the function to calculate the square root of a number n

def sqrt2(n): 
  
    # Use x as initial approximation (1)
        x = n 
    # Initialize (2)
        y = 1          
    # e decides the accuracy level 
        e = 0.000001
    # Create condition for accuracy and calculate the better guess (3)
        while(x - y > e): 
    # Get the next approximation for root using average of x and y
            x = (x + y)/2
            y = n / x 
    # Return the (approximate) square root of x.
        return x
     

In [4]:
#Ask for square root of 2 and print 100 decimals [5]. 
"{0:.100f}".format(sqrt2(2))

'1.4142135623746898698271934335934929549694061279296875000000000000000000000000000000000000000000000000'

## Task 2: 
***

<b>Use scipy.stats to verify the Chi-squared value of the table below it is approximately 24.6 and and calculate the associated p value [7].</b>


The Chi-squared test for independence is a statistical hypothesis test like a t-test. It is used to analyse whether two categorical variables are independent. In order to find Chi-square, we are going to use the SciPy package. SciPy is a Python-based open-source software for mathematics, science, and engineering [8].


|              | A   | B   | C   | D   | Total |
|-------------:|-----|-----|-----|-----|-------|
| White Collar | 90  | 60  | 104 | 95  | 349   |
| Blue Collar  | 30  | 50  | 51  | 20  | 151   |
| No Collar    | 30  | 40  | 45  | 35  | 150   |
|------------- |-----|-----|-----|-----|-------|
| Total        | 150 | 150 | 200 | 150 | 650   |
    
    
 ### About Chi-Square

The Chi-square test for independence is also called Pearson’s chi-square test. Chi-square test for independence is used in science, economics, marketing, or other various fields. There are three ways to use the Chi-square. The Chi-square test for independence shows how two sets of data are independent of each other. Chi-square of the Goodness-of-fit test shows how different your data to the expected value. The test for homogeneity determines if two or more populations have the same distribution of a single categorical variable [8,9,10].

In the section below we will implement an example of Chi-square test for independence which compares two variables in a contingency table to see if they are related. In a more general sense, it tests to see whether distributions of categorical variables differ from each another.

- A very small chi square test statistic means that your observed data fits your expected data extremely well. In other words, there is a relationship.

- A very large chi square test statistic means that the data does not fit very well. In other words, there isn’t a relationship.

The formula for the chi-square statistic used in the chi square test is:

\begin{equation}
\chi^2=\Sigma\frac{(O-E)^2}{E} \\
\text{where O is the actual value and E is the expected value.}
\end{equation}

A chi-square statistic is one way to show a relationship between two categorical variables. In statistics, there are two types of variables: numerical (countable) variables and non-numerical (categorical) variables. The chi-squared statistic is a single number that tells you how much difference exists between your observed counts and the counts you would expect if there were no relationship at all in the population.

A low value for chi-square means there is a high correlation between your two sets of data. In theory, if your observed and expected values were equal (“no difference”) then chi-square would be zero — an event that is unlikely to happen in real life. Deciding whether a chi-square test statistic is large enough to indicate a statistically significant difference isn’t as easy it seems. It would be nice if we could say a chi-square test statistic >10 means a difference, but unfortunately that isn’t the case.

To evaluate the difference you could use a p-value. First state the null hypothesis and the alternate hypothesis. Then generate a chi-square curve for your results along with a p-value. Small p-values (under 5%) usually indicate that a difference is significant (or “small enough”).

<b>Using Chi Square P-Values</b>

A chi square test will give you a p-value. The p-value will tell you if your test results are significant or not. In order to perform a chi square test and get the p-value, you need two pieces of information:


1. Degrees of freedom: You can find the degree of freedom in the third returned value when you use SciPy. The degree of freedom is used to find the p-value. The way you find the degree of freedom (dof) for 𝜒2 for independence is dof = (the number of rows - 1) X (The number of columns - 1)


2. The alpha level(α). This is chosen by you, or the researcher. The usual alpha level is 0.05 (5%), but you could also have other levels like 0.01 or 0.10.

In the example below we demostrated that the Chi-square of the table above is approximately 24.6 and we can see the P-Value is 0.00041 which is lower than 0.05, therefore we reject the null hypothesis of independence and accept that the variables have a relation. 

Finally, the array at the end of the output is the contingency table (also called crosstab) with expected values based on all of our samples. Is used in statistics to summarise the relationship between several categorical variables and in our example we can see that blue collar and no collar have similar distribution and the white collar have a higher one. 

See below steps to calculate the Chi-Square of the table requested:

In [6]:
# We add the data using Numpy dataframe and we will store our data in the table in a variable called collars[9].

import numpy as np

a1 = [90, 60, 104, 95]
a2 = [30, 50, 51, 20]
a3 = [30, 40, 45, 35]

collars = np.array([a1, a2, a3])

In [7]:
# Using SciPy’s chi2_contingency() we will get four values, 𝜒2 value, p-value, degree of freedom and expected values. 
# The data is represented in a easy to read code as SciPy give the data not organised [9]. 

from scipy import stats
stats.chi2_contingency(collars)

chi2_stat, p_val, dof, ex = stats.chi2_contingency(collars)
print("===Chi2 Stat===")
print(chi2_stat)
print("\n")
print("===Degrees of Freedom===")
print(dof)
print("\n")
print("===P-Value===")
print(p_val)
print("\n")
print("===Contingency Table===")
print(ex)

===Chi2 Stat===
24.5712028585826


===Degrees of Freedom===
6


===P-Value===
0.0004098425861096696


===Contingency Table===
[[ 80.53846154  80.53846154 107.38461538  80.53846154]
 [ 34.84615385  34.84615385  46.46153846  34.84615385]
 [ 34.61538462  34.61538462  46.15384615  34.61538462]]


## Task 3: 

<b> Research about standard deviation functions in Excel STDEV.P and STDEV.S, writing a note about the difference between them. Then use numpy to perform a simulation demonstrating that the STDEV.S calculation is a better estimate.</b>

 ### About Standar Deviation
 
It is used to evaluate how far the data is spread from the mean of data sample. It is the squire root of variance [12].
 
The standard deviation of the population is evaluated when there is minimal risk to apply the result on aggregate data. Here we take the whole population for calculating the standard deviation. The sum of squared deviation is divided by N (number of arguments).[11]

#### Difference between STDEV.P and STDEV.S

The STDEV.P function is used when your data represents the entire population and is calculated using numpy with the formula below.the squared deviation is divided by the total number of arguments, represented below as len(x).

$$ np.sqrt(np.sum((x - np.mean(x))**2)/len(x)) $$

The STDEV.S function is used when your data is a sample of the entire population. The squared deviation is divided by the total number of sample -1. It is represented as len(x)-1.
$$ np.sqrt(np.sum((x - np.mean(x))**2)/len(x)-1) $$


Since STDEV.P function considers entire data, and some factors may dominate the result standard deviation. And since it will be taken as the standard deviation for everyone in data, even for minorities, this is called <b>Biased Analysis</b>. This is why this standard deviation is recommended to use only when an analysis is non-destructive.

The STDEV.S or STDEV function is used on a small sample of the entire population, and we subtract one from the denominator (number of samples arguments). This is called <b>non-biassed analysis</b> of standard deviation. This is used when an analysis is destructive.



Important:

The STDEV.P is just a newer version of STDEVP and STDEV functions of excel. There is no significant difference between them. However, Excel recommends the use of STDEV.P function
The STDEV.P function only recognises numbers. Any other value is ignored.
Use this function when you have captured the entire population. For sample data, use STDEV.S function.
So yeah, this STDEV.P function. I hope this was informative. If you have any doubts or suggestion regarding this article or any other function of excel, be my guest and use the comment section below. I will be more than happy to hear from you guys.



References:

Task 1

1. https://www.geeksforgeeks.org/square-root-of-a-perfect-square/ - Babylonian
2. https://en.wikipedia.org/wiki/Methods_of_computing_square_roots#Babylonian_method - About babylonian
3. https://blogs.sas.com/content/iml/2016/05/16/babylonian-square-roots.html - About Babylonian SAS
4. https://github.com/ianmcloughlin/playing-with-jupyter/blob/main/playing-with-jupyter.ipynb -GitHub Ian
5. https://www.geeksforgeeks.org/precision-handling-python/ decimal
6. https://stackoverflow.com/questions/58170806/how-to-compute-and-store-the-digits-of-sqrtn-up-to-106-decimal-places

Task 2
7. https://en.wikipedia.org/w/index.php?title=Chi-squared_test&oldid=983024096
8. https://towardsdatascience.com/gentle-introduction-to-chi-square-test-for-independence-7182a7414a95 about Chi
9. https://towardsdatascience.com/running-chi-square-tests-in-python-with-die-roll-data-b9903817c51b
10. https://www.statisticshowto.com/probability-and-statistics/chi-square/

Task 3
11. https://www.exceltip.com/statistical-formulas/how-to-use-excel-stdev-p-function.html#:~:text=Let's%20Explore.-,The%20STDEV.,sample%20of%20the%20entire%20population.
12. https://www.exceltip.com/statistical-formulas/how-to-use-stdev-s-function-in-excel.html


